ALL_CURRENT_HOTKEYS = [
  "ctrl, 0",
  "ctrl, 1",
  "ctrl, 2",
  "ctrl, 3",
  "ctrl, 4",
  "ctrl, 5",
  "ctrl, 6",
  "ctrl, 7",
  "ctrl, 8",
  "ctrl, 9",
  "ctrl, a",
  "ctrl, b",
  "ctrl, c",
  "ctrl, d",
  "ctrl, e",
  "ctrl, f",
  "ctrl, g",
  "ctrl, h",
  "ctrl, i",
  "ctrl, j",
  "ctrl, k",
  "ctrl, l",
  "ctrl, m",
  "ctrl, n",
  "ctrl, o",
  "ctrl, p",
  "ctrl, q",
  "ctrl, r",
  "ctrl, s",
  "ctrl, t",
  "ctrl, u",
  "ctrl, v",
  "ctrl, w",
  "ctrl, x",
  "ctrl, y",
  "ctrl, z",
  "ctrl, tab",
  "ctrl, backspace",
  "ctrl, left",
  "ctrl, up",
  "ctrl, right",
  "ctrl, down",
  "ctrl, numpad_mult",
  "ctrl, numpad_add",
  "ctrl, numpad_separator",
  "ctrl, numpad_subtract",
  "ctrl, numpad_decimal",
  "ctrl, numpad_divide",
  "ctrl, numpad0",
  "ctrl, numpad1",
  "ctrl, numpad2",
  "ctrl, numpad3",
  "ctrl, numpad4",
  "ctrl, numpad5",
  "ctrl, numpad6",
  "ctrl, numpad7",
  "ctrl, numpad8",
  "ctrl, numpad9",
  "ctrl, f1",
  "ctrl, f2",
  "ctrl, f3",
  "ctrl, f4",
  "ctrl, f5",
  "ctrl, f6",
  "ctrl, f7",
  "ctrl, f8",
  "ctrl, f9",
  "ctrl, f10",
  "ctrl, f11",
  "ctrl, f12",
  "ctrl, f13",
  "ctrl, f14",
  "ctrl, f15",
  "ctrl, f16",
  "alt, 0",
  "alt, 1",
  "alt, 2",
  "alt, 3",
  "alt, 4",
  "alt, 5",
  "alt, 6",
  "alt, 7",
  "alt, 8",
  "alt, 9",
  "alt, a",
  "alt, b",
  "alt, c",
  "alt, d",
  "alt, e",
  "alt, f",
  "alt, g",
  "alt, h",
  "alt, i",
  "alt, j",
  "alt, k",
  "alt, l",
  "alt, m",
  "alt, n",
  "alt, o",
  "alt, p",
  "alt, q",
  "alt, r",
  "alt, s",
  "alt, t",
  "alt, u",
  "alt, v",
  "alt, w",
  "alt, x",
  "alt, y",
  "alt, z",
  "alt, tab",
  "alt, backspace",
  "alt, left",
  "alt, up",
  "alt, right",
  "alt, down",
  "alt, numpad_mult",
  "alt, numpad_add",
  "alt, numpad_separator",
  "alt, numpad_subtract",
  "alt, numpad_decimal",
  "alt, numpad_divide",
  "alt, numpad0",
  "alt, numpad1",
  "alt, numpad2",
  "alt, numpad3",
  "alt, numpad4",
  "alt, numpad5",
  "alt, numpad6",
  "alt, numpad7",
  "alt, numpad8",
  "alt, numpad9",
  "alt, f1",
  "alt, f2",
  "alt, f3",
  "alt, f4",
  "alt, f5",
  "alt, f6",
  "alt, f7",
  "alt, f8",
  "alt, f9",
  "alt, f10",
  "alt, f11",
  "alt, f12",
  "alt, f13",
  "alt, f14",
  "alt, f15",
  "alt, f16",
  "shift, 0",
  "shift, 1",
  "shift, 2",
  "shift, 3",
  "shift, 4",
  "shift, 5",
  "shift, 6",
  "shift, 7",
  "shift, 8",
  "shift, 9",
  "shift, a",
  "shift, b",
  "shift, c",
  "shift, d",
  "shift, e",
  "shift, f",
  "shift, g",
  "shift, h",
  "shift, i",
  "shift, j",
  "shift, k",
  "shift, l",
  "shift, m",
  "shift, n",
  "shift, o",
  "shift, p",
  "shift, q",
  "shift, r",
  "shift, s",
  "shift, t",
  "shift, u",
  "shift, v",
  "shift, w",
  "shift, x",
  "shift, y",
  "shift, z",
  "shift, tab",
  "shift, backspace",
  "shift, left",
  "shift, up",
  "shift, right",
  "shift, down",
  "shift, numpad_mult",
  "shift, numpad_add",
  "shift, numpad_separator",
  "shift, numpad_subtract",
  "shift, numpad_decimal",
  "shift, numpad_divide",
  "shift, numpad0",
  "shift, numpad1",
  "shift, numpad2",
  "shift, numpad3",
  "shift, numpad4",
  "shift, numpad5",
  "shift, numpad6",
  "shift, numpad7",
  "shift, numpad8",
  "shift, numpad9",
  "shift, f1",
  "shift, f2",
  "shift, f3",
  "shift, f4",
  "shift, f5",
  "shift, f6",
  "shift, f7",
  "shift, f8",
  "shift, f9",
  "shift, f10",
  "shift, f11",
  "shift, f12",
  "shift, f13",
  "shift, f14",
  "shift, f15",
  "shift, f16",
  "ctrl + alt, 0",
  "ctrl + alt, 1",
  "ctrl + alt, 2",
  "ctrl + alt, 3",
  "ctrl + alt, 4",
  "ctrl + alt, 5",
  "ctrl + alt, 6",
  "ctrl + alt, 7",
  "ctrl + alt, 8",
  "ctrl + alt, 9",
  "ctrl + alt, a",
  "ctrl + alt, b",
  "ctrl + alt, c",
  "ctrl + alt, d",
  "ctrl + alt, e",
  "ctrl + alt, f",
  "ctrl + alt, g",
  "ctrl + alt, h",
  "ctrl + alt, i",
  "ctrl + alt, j",
  "ctrl + alt, k",
  "ctrl + alt, l",
  "ctrl + alt, m",
  "ctrl + alt, n",
  "ctrl + alt, o",
  "ctrl + alt, p",
  "ctrl + alt, q",
  "ctrl + alt, r",
  "ctrl + alt, s",
  "ctrl + alt, t",
  "ctrl + alt, u",
  "ctrl + alt, v",
  "ctrl + alt, w",
  "ctrl + alt, x",
  "ctrl + alt, y",
  "ctrl + alt, z",
  "ctrl + alt, tab",
  "ctrl + alt, backspace",
  "ctrl + alt, left",
  "ctrl + alt, up",
  "ctrl + alt, right",
  "ctrl + alt, down",
  "ctrl + alt, numpad_mult",
  "ctrl + alt, numpad_add",
  "ctrl + alt, numpad_separator",
  "ctrl + alt, numpad_subtract",
  "ctrl + alt, numpad_decimal",
  "ctrl + alt, numpad_divide",
  "ctrl + alt, numpad0",
  "ctrl + alt, numpad1",
  "ctrl + alt, numpad2",
  "ctrl + alt, numpad3",
  "ctrl + alt, numpad4",
  "ctrl + alt, numpad5",
  "ctrl + alt, numpad6",
  "ctrl + alt, numpad7",
  "ctrl + alt, numpad8",
  "ctrl + alt, numpad9",
  "ctrl + alt, f1",
  "ctrl + alt, f2",
  "ctrl + alt, f3",
  "ctrl + alt, f4",
  "ctrl + alt, f5",
  "ctrl + alt, f6",
  "ctrl + alt, f7",
  "ctrl + alt, f8",
  "ctrl + alt, f9",
  "ctrl + alt, f10",
  "ctrl + alt, f11",
  "ctrl + alt, f12",
  "ctrl + alt, f13",
  "ctrl + alt, f14",
  "ctrl + alt, f15",
  "ctrl + alt, f16",
  "ctrl + shift, 0",
  "ctrl + shift, 1",
  "ctrl + shift, 2",
  "ctrl + shift, 3",
  "ctrl + shift, 4",
  "ctrl + shift, 5",
  "ctrl + shift, 6",
  "ctrl + shift, 7",
  "ctrl + shift, 8",
  "ctrl + shift, 9",
  "ctrl + shift, a",
  "ctrl + shift, b",
  "ctrl + shift, c",
  "ctrl + shift, d",
  "ctrl + shift, e",
  "ctrl + shift, f",
  "ctrl + shift, g",
  "ctrl + shift, h",
  "ctrl + shift, i",
  "ctrl + shift, j",
  "ctrl + shift, k",
  "ctrl + shift, l",
  "ctrl + shift, m",
  "ctrl + shift, n",
  "ctrl + shift, o",
  "ctrl + shift, p",
  "ctrl + shift, q",
  "ctrl + shift, r",
  "ctrl + shift, s",
  "ctrl + shift, t",
  "ctrl + shift, u",
  "ctrl + shift, v",
  "ctrl + shift, w",
  "ctrl + shift, x",
  "ctrl + shift, y",
  "ctrl + shift, z",
  "ctrl + shift, tab",
  "ctrl + shift, backspace",
  "ctrl + shift, left",
  "ctrl + shift, up",
  "ctrl + shift, right",
  "ctrl + shift, down",
  "ctrl + shift, numpad_mult",
  "ctrl + shift, numpad_add",
  "ctrl + shift, numpad_separator",
  "ctrl + shift, numpad_subtract",
  "ctrl + shift, numpad_decimal",
  "ctrl + shift, numpad_divide",
  "ctrl + shift, numpad0",
  "ctrl + shift, numpad1",
  "ctrl + shift, numpad2",
  "ctrl + shift, numpad3",
  "ctrl + shift, numpad4",
  "ctrl + shift, numpad5",
  "ctrl + shift, numpad6",
  "ctrl + shift, numpad7",
  "ctrl + shift, numpad8",
  "ctrl + shift, numpad9",
  "ctrl + shift, f1",
  "ctrl + shift, f2",
  "ctrl + shift, f3",
  "ctrl + shift, f4",
  "ctrl + shift, f5",
  "ctrl + shift, f6",
  "ctrl + shift, f7",
  "ctrl + shift, f8",
  "ctrl + shift, f9",
  "ctrl + shift, f10",
  "ctrl + shift, f11",
  "ctrl + shift, f12",
  "ctrl + shift, f13",
  "ctrl + shift, f14",
  "ctrl + shift, f15",
  "ctrl + shift, f16",
  "alt + shift, 0",
  "alt + shift, 1",
  "alt + shift, 2",
  "alt + shift, 3",
  "alt + shift, 4",
  "alt + shift, 5",
  "alt + shift, 6",
  "alt + shift, 7",
  "alt + shift, 8",
  "alt + shift, 9",
  "alt + shift, a",
  "alt + shift, b",
  "alt + shift, c",
  "alt + shift, d",
  "alt + shift, e",
  "alt + shift, f",
  "alt + shift, g",
  "alt + shift, h",
  "alt + shift, i",
  "alt + shift, j",
  "alt + shift, k",
  "alt + shift, l",
  "alt + shift, m",
  "alt + shift, n",
  "alt + shift, o",
  "alt + shift, p",
  "alt + shift, q",
  "alt + shift, r",
  "alt + shift, s",
  "alt + shift, t",
  "alt + shift, u",
  "alt + shift, v",
  "alt + shift, w",
  "alt + shift, x",
  "alt + shift, y",
  "alt + shift, z",
  "alt + shift, tab",
  "alt + shift, backspace",
  "alt + shift, left",
  "alt + shift, up",
  "alt + shift, right",
  "alt + shift, down",
  "alt + shift, numpad_mult",
  "alt + shift, numpad_add",
  "alt + shift, numpad_separator",
  "alt + shift, numpad_subtract",
  "alt + shift, numpad_decimal",
  "alt + shift, numpad_divide",
  "alt + shift, numpad0",
  "alt + shift, numpad1",
  "alt + shift, numpad2",
  "alt + shift, numpad3",
  "alt + shift, numpad4",
  "alt + shift, numpad5",
  "alt + shift, numpad6",
  "alt + shift, numpad7",
  "alt + shift, numpad8",
  "alt + shift, numpad9",
  "alt + shift, f1",
  "alt + shift, f2",
  "alt + shift, f3",
  "alt + shift, f4",
  "alt + shift, f5",
  "alt + shift, f6",
  "alt + shift, f7",
  "alt + shift, f8",
  "alt + shift, f9",
  "alt + shift, f10",
  "alt + shift, f11",
  "alt + shift, f12",
  "alt + shift, f13",
  "alt + shift, f14",
  "alt + shift, f15",
  "alt + shift, f16",
  "ctrl + alt + shift, 0",
  "ctrl + alt + shift, 1",
  "ctrl + alt + shift, 2",
  "ctrl + alt + shift, 3",
  "ctrl + alt + shift, 4",
  "ctrl + alt + shift, 5",
  "ctrl + alt + shift, 6",
  "ctrl + alt + shift, 7",
  "ctrl + alt + shift, 8",
  "ctrl + alt + shift, 9",
  "ctrl + alt + shift, a",
  "ctrl + alt + shift, b",
  "ctrl + alt + shift, c",
  "ctrl + alt + shift, d",
  "ctrl + alt + shift, e",
  "ctrl + alt + shift, f",
  "ctrl + alt + shift, g",
  "ctrl + alt + shift, h",
  "ctrl + alt + shift, i",
  "ctrl + alt + shift, j",
  "ctrl + alt + shift, k",
  "ctrl + alt + shift, l",
  "ctrl + alt + shift, m",
  "ctrl + alt + shift, n",
  "ctrl + alt + shift, o",
  "ctrl + alt + shift, p",
  "ctrl + alt + shift, q",
  "ctrl + alt + shift, r",
  "ctrl + alt + shift, s",
  "ctrl + alt + shift, t",
  "ctrl + alt + shift, u",
  "ctrl + alt + shift, v",
  "ctrl + alt + shift, w",
  "ctrl + alt + shift, x",
  "ctrl + alt + shift, y",
  "ctrl + alt + shift, z",
  "ctrl + alt + shift, tab",
  "ctrl + alt + shift, backspace",
  "ctrl + alt + shift, left",
  "ctrl + alt + shift, up",
  "ctrl + alt + shift, right",
  "ctrl + alt + shift, down",
  "ctrl + alt + shift, numpad_mult",
  "ctrl + alt + shift, numpad_add",
  "ctrl + alt + shift, numpad_separator",
  "ctrl + alt + shift, numpad_subtract",
  "ctrl + alt + shift, numpad_decimal",
  "ctrl + alt + shift, numpad_divide",
  "ctrl + alt + shift, numpad0",
  "ctrl + alt + shift, numpad1",
  "ctrl + alt + shift, numpad2",
  "ctrl + alt + shift, numpad3",
  "ctrl + alt + shift, numpad4",
  "ctrl + alt + shift, numpad5",
  "ctrl + alt + shift, numpad6",
  "ctrl + alt + shift, numpad7",
  "ctrl + alt + shift, numpad8",
  "ctrl + alt + shift, numpad9",
  "ctrl + alt + shift, f1",
  "ctrl + alt + shift, f2",
  "ctrl + alt + shift, f3",
  "ctrl + alt + shift, f4",
  "ctrl + alt + shift, f5",
  "ctrl + alt + shift, f6",
  "ctrl + alt + shift, f7",
  "ctrl + alt + shift, f8",
  "ctrl + alt + shift, f9",
  "ctrl + alt + shift, f10",
  "ctrl + alt + shift, f11",
  "ctrl + alt + shift, f12",
  "ctrl + alt + shift, f13",
  "ctrl + alt + shift, f14",
  "ctrl + alt + shift, f15",
  "ctrl + alt + shift, f16",
]